version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: rollup
    versions:
    - 2.38.1
    - 2.38.2
    - 2.38.3
    - 2.38.4
    - 2.38.5
    - 2.39.0
    - 2.39.1
    - 2.40.0
    - 2.41.0
    - 2.41.1
    - 2.41.2
    - 2.41.3
    - 2.41.4
    - 2.41.5
    - 2.42.0
    - 2.42.1
    - 2.42.2
    - 2.42.3
    - 2.42.4
    - 2.43.0
    - 2.43.1
    - 2.44.0
    - 2.45.0
    - 2.45.1
    - 2.45.2
  - dependency-name: terser
    versions:
    - 5.5.1
    - 5.6.0
    - 5.6.1
  - dependency-name: chai
    versions:
    - 4.3.0
    - 4.3.1
    - 4.3.2
    - 4.3.3
