environment:
  matrix:
    - nodejs_version: "0.10"
    - nodejs_version: "0.11"
    - nodejs_version: "0.12"
    - nodejs_version: "1.8"
    - nodejs_version: "2.5"
    - nodejs_version: "3.3"
    - nodejs_version: "4.2"
    - nodejs_version: "5.3"
    - nodejs_version: "6.2"
    - nodejs_version: "6.3"
    - nodejs_version: "6.5"
    - nodejs_version: "6.6"
    - nodejs_version: "6.9"
    - nodejs_version: "7.0"
    - nodejs_version: "7.1"
    - nodejs_version: "7.2"
    - nodejs_version: "7.3"
    - nodejs_version: "7.4"
    - nodejs_version: "7.5"
    - nodejs_version: "7.6"
    - nodejs_version: "7.7"
    - nodejs_version: "7.8"
    - nodejs_version: "7.9"
platform:
  - x86
  - x64
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - npm install mocha
  - npm install istanbul
build: off
test_script:
  - node --version
  - npm --version
  - npm run test-ci
  - npm install coveralls
  - type .\coverage\lcov.info | node ./node_modules/coveralls/bin/coveralls.js
version: "{build}"
